import type { Metadata } from "next";
import "./globals.css";

import { Header } from "@/components/Header";
import { BottomNavBar } from "@/components/BottomNavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="mx-auto flex h-screen max-w-md flex-col">
        <Header />
        <main className="flex-grow">{children}</main>
        <BottomNavBar />
      </body>
    </html>
  );
}
