import type { Metadata } from "next";
import "./globals.css";

import { Header } from "@/components/Header";
import { BottomNavBar } from "@/components/BottomNavBar";

import {
  geistSans,
  geistMono,
  montserrat,
  raleway,
  nunito,
  quicksand,
  architectsDaughter,
  comfortaa,
  pretendard,
  suit,
  nanumSquareNeo,
  paperlogy,
  sCoreDream,
} from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${raleway.variable} ${nunito.variable} ${quicksand.variable} ${architectsDaughter.variable} ${comfortaa.variable} ${pretendard.variable} ${suit.variable} ${nanumSquareNeo.variable} ${paperlogy.variable} ${sCoreDream.variable}`}
    >
      <body className="mx-auto flex h-screen max-w-md flex-col shadow-lg">
        <Header />
        <main className="scrollbar-hidden flex-grow overflow-y-auto">
          {children}
        </main>
        <BottomNavBar />
      </body>
    </html>
  );
}
